%YAML 1.1
---
gfVersion: v1.0
class: workflow

# metadata
name: Hello World Workflow
description: Hello World one-step workflow
documentation_uri:
repo_uri: 'https://gitlab.com/geneflow/workflows/workflow-template.git'
version: '0.1'
username: user

final_output:
- hello

# inputs
inputs:
  file:
    label: Dummy Input File
    description: Dummy input file
    type: File
    enable: true
    visible: true

# parameters

# steps
steps:
  hello:
    app: apps/hello-world-gf-0.1/app.yaml
    depend: []
    template:
      file: '{workflow->file}'
      output: output.txt
